#!/bin/bash

# run "bluetoothctl" to find the MAC address of your device.
MAC="00:00:00:00:00:00"

if hcitool con | grep -q "$MAC"
then
    echo -e "disconnect $MAC \nquit" | bluetoothctl
else
    echo -e "connect $MAC \nquit" | bluetoothctl
fi
